"""
Author: Hua Zou
Aim: A workflow to process paired-end stranded amplicon sequence by Snakemake.
Date: July 30 2019
Run: snakemake -s Snakefile
"""
import os
import sys
import shutil
import pandas as pd

configfile: "config.yaml"

samples = pd.read_csv(config["samples"], sep="\t", index_col=["sampleid"])


rule all:
    input:
        os.path.join(config["results"]["trim"], "Sample_path.qiime2.tsv")

include: "rules/00.fastqc.snk"
include: "rules/01.trim.snk"
include: "rules/02.fastq2qza.snk"
include: "rules/03.feature_table.snk"
include: "rules/04.Phylogenetic_tree.snk"
include: "rules/05.diversity.snk" 
"""
include: "rules/06.assign_taxonomy.snk"
include: "rules/07.picrust.snk" 
"""