---
title: "Wilcoxon rank sum test"
date: "Created: 2021-01-12 Modified: `r Sys.Date()`"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(tidyverse)
library(patchwork)
library(tibble)
library(ggplot2)
library(data.table)

grp <- c("lupus", "Control")
grp.col <- c("#283891", "#C1272D")
```


### load data
```{r}
phen <- read.csv("../../Result/phenotype/phenotype_20200111.csv")
pm.prf <- fread("../../Result/profile/final_phylum_trim.tsv") 
gs.prf <- fread("../../Result/profile/final_genus_trim.tsv")
sp.prf <- fread("../../Result/profile/final_species_trim.tsv")
```


### Function
```{r}
stamp_fun <- function(profile  = pm.prf,
                      metadata = phen,
                      num=10){
  
  # profile  = pm.prf
  # metadata = phen
  # num = 10
  
  top_tax <-  profile %>% column_to_rownames("V1") %>%
      t() %>% data.frame() %>%
      summarise_each(mean) %>%
      tidyr::gather(key="tax", value="value") %>%
      arrange(desc(value)) %>%
      slice(c(1:num)) %>%
      mutate(tax=as.character(tax),
             tax2=tax)
  
  mdat <- profile %>% filter(apply(dplyr::select(., -one_of("V1")), 1, 
                       function(x){mean(x)}) > 0.00001) %>%
                  data.frame(.) %>%
          filter(V1%in%top_tax$tax2) %>%
          column_to_rownames("V1") %>%
          t() %>% data.frame() %>%
          rownames_to_column("SampleID") %>%
          inner_join(metadata %>% dplyr::select(c("SampleID", "Group")), 
                     by = "SampleID") %>%
          mutate(Group=factor(Group, levels = grp)) %>%
          column_to_rownames("SampleID")
  
  diff_t <- mdat %>% 
      select_if(is.numeric) %>%
      map_df(~ broom::tidy(t.test(. ~ Group, data = mdat)), .id = 'var') %>%
      mutate(p.adjust=p.adjust(as.numeric(p.value), "bonferroni")) #%>%
      #filter(p.adjust < 1)
  
  abun.bar <- mdat %>% select(c(diff_t$var, "Group")) %>% 
      gather(key = "variable", value = "value", -Group) %>% 
      group_by(variable, Group) %>% 
      summarise(Mean = mean(value)) %>%
      ungroup()
  
  diff_t_mean <- diff_t %>% select(c("var", "estimate", 
                                   "conf.low", "conf.high",
                                   "p.adjust")) %>%
                mutate(Group=ifelse(estimate >0, levels(mdat$Group)[1],
                                        levels(mdat$Group)[2])) %>%
                arrange(desc(estimate))
  
  # left barplot
  cbbPalette <- grp.col
  abun.bar$variable <- factor(abun.bar$variable, levels = rev(diff_t_mean$var))
  p1 <- ggplot(abun.bar, aes(x=variable, y=Mean, fill=Group)) +
      scale_x_discrete(limits = levels(diff_t_mean$var)) +
      coord_flip() +
      xlab("") +
      ylab("Mean proportion (%)") +
      theme(panel.background = element_rect(fill = 'transparent'),
            panel.grid = element_blank(),
            axis.ticks.length = unit(0.4,"lines"), 
            axis.ticks = element_line(color='black'),
            axis.line = element_line(colour = "black"),
            axis.title.x = element_text(colour='black', size=12,face = "bold"),
            axis.text.x = element_text(colour='black', size=10, face = "bold"),
            text = element_text(size=8, color="black", family="serif"),
            legend.title=element_blank(),
            legend.text=element_text(size=12,face = "bold",colour = "black",
                                     margin = margin(r = 20)),
            #legend.position = c(-1,-0.1),
            legend.position = c(-0.1,-0.05),
            legend.direction = "horizontal",
            legend.key.width = unit(0.8,"cm"),
            legend.key.height = unit(0.5,"cm"))

  for (i in 1:(nrow(diff_t_mean) - 1)){
      p1 <- p1 + annotate('rect', xmin = i+0.5, xmax = i+1.5, ymin = -Inf, ymax = Inf, 
                          fill = ifelse(i %% 2 == 0, 'white', 'gray95'))  
  } 
  
  p1 <- p1 + geom_bar(stat = "identity", position = "dodge",width = 0.7,colour = "black") +
      scale_fill_manual(values=cbbPalette)+
      theme(axis.text.y = element_text(colour='black', size=10, face = "italic"))
  
  
  ## right scatterplot
  diff_t_mean$var <- factor(diff_t_mean$var,levels = levels(abun.bar$variable))
  diff_t_mean$p.adjust <- signif(diff_t_mean$p.adjust, 3)
  diff_t_mean$p.adjust <- as.character(diff_t_mean$p.adjust)
  
  p2 <- ggplot(diff_t_mean, aes(x=var, y=estimate, fill = Group)) +
      theme(panel.background = element_rect(fill = 'transparent'),
            panel.grid = element_blank(),
            axis.ticks.length = unit(0.4,"lines"), 
            axis.ticks = element_line(color='black'),
            axis.line = element_line(colour = "black"),
            axis.title.x = element_text(colour='black', size=12,face = "bold"),
            axis.text = element_text(colour='black',size=10,face = "bold"),
            axis.text.y = element_blank(),
            text = element_text(size=8, color="black", family="serif"),
            legend.position = "none",
            axis.line.y = element_blank(),
            axis.ticks.y = element_blank(),
            plot.title = element_text(size = 15,face = "bold",colour = "black",hjust = 0.5)) +
      scale_x_discrete(limits = levels(diff_t_mean$var)) +
      coord_flip() +
      xlab("") +
      ylab("Difference in mean proportions (%)") +
      labs(title="95% confidence intervals") 
  
  for (i in 1:(nrow(diff_t_mean) - 1)){
      p2 <- p2 + annotate('rect', xmin = i+0.5, xmax = i+1.5, ymin = -Inf, ymax = Inf, 
                          fill = ifelse(i %% 2 == 0, 'white', 'gray95'))  
  } 
  
  
  p2 <- p2 +
      geom_errorbar(aes(ymin = conf.low, ymax = conf.high), 
                    position = position_dodge(0.8), width = 0.5, size = 0.5) +
      geom_point(shape = 21,size = 3) +
      scale_fill_manual(values=cbbPalette) +
      geom_hline(aes(yintercept = 0), linetype = 'dashed', color = 'black')
      
      
  p3 <- ggplot(diff_t_mean, aes(x=var, y=estimate, fill = Group)) +
      geom_text(aes(y = 0,x = var),label = diff_t_mean$p.adjust,
                hjust = 0,fontface = "bold",inherit.aes = FALSE,size = 3) +
      geom_text(aes(x = nrow(diff_t_mean)/2 +0.5,y = 0.85),label = "P-value (corrected)",
               srt = 90,fontface = "bold",size = 5) +
      coord_flip() +
      ylim(c(0,1)) +
      theme(panel.background = element_blank(),
            panel.grid = element_blank(),
            axis.line = element_blank(),
            axis.ticks = element_blank(),
            axis.text = element_blank(),
            axis.title = element_blank())


  pl <- p1 + p2 + p3 + plot_layout(widths = c(4, 6, 2))
  
  return(pl)
}
```


### species
```{r}
speciespl <- stamp_fun(profile = sp.prf, metadata = phen, num = 30)
speciespl

dir <- "../../Result/STAMP"
if(!dir.exists(dir)){
  dir.create(dir)
}
species.path <- paste(dir, "STAMP_species.pdf", sep = "/")
ggsave(filename = species.path, plot = speciespl, width = 12, height = 7, dpi = 600)
```


### genus
```{r}
genuspl <- stamp_fun(profile = gs.prf, metadata = phen, num = 20)
genuspl

dir <- "../../Result/STAMP"
if(!dir.exists(dir)){
  dir.create(dir)
}
genus.path <- paste(dir, "STAMP_genus.pdf", sep = "/")
ggsave(filename = genus.path, plot = genuspl, width = 12, height = 7, dpi = 600)
```


### phylum
```{r, fig.height=5, fig.width=12}
phylumpl <- stamp_fun(profile = pm.prf, metadata = phen, num = 10)
phylumpl

dir <- "../../Result/STAMP"
if(!dir.exists(dir)){
  dir.create(dir)
}
phylum.path <- paste(dir, "STAMP_phylum.pdf", sep = "/")
ggsave(filename = phylum.path, plot = phylumpl, width = 12, height = 6, dpi = 600)
```

### version
```{r}
sessionInfo()
```
