---
title: "Wilcoxon rank sum test"
date: "Created: 2021-01-12 Modified: `r Sys.Date()`"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(scales)
library(varhandle)


grp <- c("lupus", "Control")
grp.col <- c("#283891", "#C1272D")
```


### load data
```{r}
phen <- read.csv("../../Result/phenotype/phenotype_20200111.csv")
pm.prf <- fread("../../Result/profile/final_phylum_trim.tsv") 
gs.prf <- fread("../../Result/profile/final_genus_trim.tsv")
sp.prf <- fread("../../Result/profile/final_species_trim.tsv")
```


### Function
```{r}
wilcox_fun <- function(x, y, DNAID, GROUP,
                       grp1=NULL, grp2=NULL){
  
  # x=phylum 
  # y=phen
  # DNAID="SampleID"
  # GROUP="Group"
  
  # determine x with two cols and names are corret
  phe <- x %>% select(c(DNAID, GROUP))
  colnames(phe)[which(colnames(phe) == DNAID)] <- "SampleID"
  colnames(phe)[which(colnames(phe) == GROUP)] <- "Stage"
  if (length(which(colnames(phe)%in%c("SampleID","Stage"))) != 2){
    warning("x without 2 cols: DNAID, GROUP")
  }
  
  # select groups
  if(length(grp1)){
    phe.cln <- phe %>% filter(Stage%in%c(grp1, grp2)) %>%
      mutate(Stage=factor(Stage, levels = c(grp1, grp2)))
    pr <- c(grp1, grp2)
  } else{
    phe.cln <- phe %>% mutate(Stage=factor(Stage))
    pr <- levels(phe.cln$Stage)
  }
  
  if (length(levels(phe.cln$Stage)) > 2) {
    stop("The levels of `group` are more than 2")
  }
  
  # profile
  sid <- intersect(phe.cln$SampleID, colnames(y))
  prf <- y %>% select(sid) %>%
    rownames_to_column("tmp") %>%
    filter(apply(select(., -one_of("tmp")), 1, 
                 function(x){sum(x > 0)/length(x)}) > 0.2) %>%
    data.frame() %>% column_to_rownames("tmp") %>%
    t() %>% data.frame()
  
  # judge no row of profile filter
  if (ncol(prf) == 0) {
    stop("No row of profile to be choosed\n")
  }
  
  # merge phenotype and profile
  mdat <- inner_join(phe.cln %>% filter(SampleID%in%sid),
                     prf %>% rownames_to_column("SampleID"),
                     by = "SampleID")
  dat.phe <- mdat %>% select(c(1:2))
  dat.prf <- mdat %>% select(-2)
  
  res <- apply(dat.prf[, -1], 2, function(x, grp){
    dat <- as.numeric(x)
    p <- signif(wilcox.test(dat ~ grp, paired = F)$p.value, 6)
    # median
    md <- signif(median(dat), 4)
    mdn <- signif(tapply(dat, grp, median), 4)
    if ( mdn[1] > mdn[2] & p < 0.05) {
      enrich1 <- pr[1]
    } else if (mdn[1] < mdn[2] & p < 0.05) {
      enrich1 <- pr[2]
    } else if (p > 0.05 | mdn[1] == mdn[2]){
      enrich1 <- "No significance"
    }
    
    # rank
    rk <- rank(dat)
    rnk <- signif(tapply(rk, grp, mean), 4)
    if ( rnk[1] > rnk[2] & p < 0.05) {
      enrich2 <- pr[1]
    } else if (rnk[1] < rnk[2] & p < 0.05) {
      enrich2 <- pr[2]
    } else if (p > 0.05 | rnk[1] == rnk[2]){
      enrich2 <- "No significance"
    }
    occ <- signif(tapply(dat, grp, function(x){
      round(sum(x > 0)/length(x), 4)}), 4)
    
    res <- c(p,enrich1,enrich2,occ,md,mdn,rnk)
    return(res)
  }, dat.phe$Stage) %>%
    t(.) %>% data.frame(.) %>%
    rownames_to_column("type") %>%
    varhandle::unfactor(.)
  
  colnames(res)[2:11] <- c("Pvalue", "Enrich_median", "Enrich_rank",
                           paste0(pr, "_occurence"), "median_all",
                           paste0(pr, "_median"), paste0(pr, "_rank"))
  res$Block <- paste0(pr[1], "_vs_", pr[2])
  number <- as.numeric(table(dat.phe$Stage))
  res$Num <- paste0(pr[1], number[1], "_vs_",
                    pr[2], number[2])
  res.cln <- res %>% select(c(1,12:13, 2:11)) %>%
    mutate(Pvalue=as.numeric(Pvalue)) %>%
    mutate(FDR=p.adjust(Pvalue, method = "BH")) %>%
    arrange(FDR, Pvalue)
  res2 <- res.cln[,c(1:4,14,5:13)]
  
  
  # scale profile
  dat.prf.cln <- prf[, -1]
  dat.phe.cln <- dat.phe %>% mutate(Group=ifelse(Stage==pr[1], 0, 1))
  idx <- which(colnames(dat.phe.cln) == "Group")
  
  # glm result for odd ratios 95%CI
  glmFun <- function(m, n){
    dat.glm <- data.frame(group=m, marker=scale(n, center=T, scale=T))
    model <- summary(glm(group ~ marker, data = dat.glm,
                         family = binomial(link = "logit")))
    res <- signif(exp(model$coefficients["marker",1]) +
                    qnorm(c(0.025,0.5,0.975)) * model$coefficients["marker",1], 2)
    
    return(res)
  }
  
  glm_res <- t(apply(dat.prf.cln, 2, function(x, group){
    res <- glmFun(group, as.numeric(x))
    return(res)
  }, group = dat.phe.cln[, idx]))
  Odd <- glm_res %>% data.frame() %>%
    setNames(c("upper", "expected","lower")) %>%
    mutate("Odds Ratio (95% CI)" = paste0(expected, " (", lower, ";", upper, ")"))
  Odd$type <- rownames(glm_res)
  
  res_merge <- inner_join(res2,
                          Odd[, c(4:5)], by = "type")
  
  return(res_merge)
}


heatFun <- function(profile=phylum, 
                    test=phylum_wilcox,
                    num=20){
  
    # profile=phylum
    # test=family_wilcox
    # num=20

    prf <- profile %>% rownames_to_column("type") %>%
      filter(type%in%test$type) %>%
      column_to_rownames("type")
    
    mdat <- inner_join(phen %>% select(SampleID, Group),
                       prf %>% t() %>% 
                        data.frame() %>%
                        rownames_to_column("SampleID"),
                       by = "SampleID") 
    mdat.total.mean <-  mdat %>%
      select(-c("SampleID", "Group")) %>%
      summarise_each(mean) %>%
      tidyr::gather(key="tax", value="value") %>%
      arrange(desc(value)) %>%
      slice(c(1:num)) %>%
      mutate(tax=as.character(tax))

  dat <- test %>% select(type, Pvalue, Enrich_rank, Control_rank, lupus_rank) %>%
    filter(type%in%unique(mdat.total.mean$tax))
  dat_es <- dat %>% select(type, Control_rank, lupus_rank) %>%
    column_to_rownames("type")%>%
    setNames(grp) %>% 
    mutate(lupus=as.numeric(lupus),
           Control=as.numeric(Control))
  rownames(dat_es) <- gsub("\\.", ";", dat$type)
  
  dat_note <- dat %>% select(type, Pvalue, Enrich_rank) %>%
     mutate(lupus=ifelse(Pvalue < 0.05 & Enrich_rank=="lupus", "*", ""),
            Control=ifelse(Pvalue < 0.05 & Enrich_rank=="Control", 
                          ifelse(Pvalue < 0.01, "**", "*"), "")) %>%
     select(type, Control, lupus) %>%
     mutate(type=gsub("\\.", ";", type)) %>%
     column_to_rownames("type")
  

  require(RColorBrewer)
  mycol <- colorRampPalette(c("#19499B", "white", "#E5211A"))(100)
  newnames <- lapply(rownames(dat_es), function(x){bquote(italic(.(x)))})
  
  pheatmap(mat = dat_es,  
           color = mycol,
           scale = "row", 
           cluster_row = FALSE,
           cluster_cols = FALSE,
           fontsize = 8, 
           cellwidth = 20, 
           cellheight = 20, 
           show_colnames = T,
           border_color = "black",
           display_numbers = dat_note,
           fontsize_number = 20,
           number_color = "white",
           labels_row = as.expression(newnames))
}
```


### species
```{r}
species <- sp.prf %>% column_to_rownames("V1")
species_wilcox <- wilcox_fun(phen, species, "SampleID", "Group")
DT::datatable(species_wilcox)

dir_wilcox <- "../../Result/wilcox"
if(!dir.exists(dir_wilcox)){
  dir.create(dir_wilcox)
}
species.path.wilcox <- paste(dir_wilcox, "final_species_trim_wilcox.csv", sep = "/")
write.csv(species_wilcox, file = species.path.wilcox, row.names = F)

species.path <- paste(dir_wilcox, "heatmap_species_wilcox.pdf", sep = "/")
pdf(file = species.path, width = 15, height = 7)
heatFun(profile = species, test = species_wilcox, num = 20)
dev.off()
```


### genus
```{r}
genus <- gs.prf %>% column_to_rownames("V1")
genus_wilcox <- wilcox_fun(phen, genus, "SampleID", "Group")
DT::datatable(genus_wilcox)

dir_wilcox <- "../../Result/wilcox"
if(!dir.exists(dir_wilcox)){
  dir.create(dir_wilcox)
}
genus.path.wilcox <- paste(dir_wilcox, "final_genus_trim_wilcox.csv", sep = "/")
write.csv(genus_wilcox, file = genus.path.wilcox, row.names = F)

genus.path <- paste(dir_wilcox, "heatmap_genus_wilcox.pdf", sep = "/")
pdf(file = genus.path, width = 15, height = 7)
heatFun(profile = genus, test = genus_wilcox, num = 20)
dev.off()
```


### phylum
```{r, fig.height=5, fig.width=12}
phylum <- pm.prf %>% column_to_rownames("V1")
phylum_wilcox <- wilcox_fun(phen, phylum, "SampleID", "Group")
DT::datatable(phylum_wilcox)

dir_wilcox <- "../../Result/wilcox"
if(!dir.exists(dir_wilcox)){
  dir.create(dir_wilcox)
}
phylum.path.wilcox <- paste(dir_wilcox, "final_phylum_trim_wilcox.csv", sep = "/")
write.csv(phylum_wilcox, file = phylum.path.wilcox, row.names = F)

phylum.path <- paste(dir_wilcox, "heatmap_phylum_wilcox.pdf", sep = "/")
pdf(file = phylum.path, width = 15, height = 7)
heatFun(profile = phylum, test = phylum_wilcox, num = 5)
dev.off()
```

### version
```{r}
sessionInfo()
```
