samples: "6samples.path.tsv"

params:
  index:
    cpu:  20
    gtf:  "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.gtf"
    fa :  "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.fa"
  trim:
    adapter1:  "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
    adapter2:  "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
    quality:      30
    error:        0.1 
    length:       99
    stringency:   5 
  alignment:
    index:     "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/STAR_index"
    cpu:       20
    matchNmin: 50
    misNmax:   100
  genecount:
    gtf: "/disk/user/zouhua/pipeline/dataset/00.RNA_seq/database/chr22_with_ERCC92.gtf"
    cpu: 2
    gene: "gene_id"
    type: "exon"
    phred_cutoff: 5

  
result:
  index:       "star_result/00.index"
  fastqc:      "star_result/01.fastqc"
  trim:        "star_result/02.trim"   
  alignment:   "star_result/03.alignment"   
  genecount:   "star_result/04.genecount"
  multiqc:     "star_result/05.multiqc"


logs:
  index:       "star_result/logs/00.index"
  fastqc:      "star_result/logs/01.fastqc"
  trim:        "star_result/logs/02.trim"
  alignment:   "star_result/logs/03.alignment"
  genecount:   "star_result/logs/04.genecount"
  multiqc:     "star_result/logs/05.multiqc"
