---
title: "MaAsLin2: Multivariable Association in Population-scale Meta-omics Studies"
date: "Created: 2021-05-17 Modified: `r Sys.Date()`"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)
library(Maaslin2)
library(ggplot2)
```


### load data
```{r}
phen <- read.csv("../../Result/phenotype/phenotype_20200111.csv")
sp.prf <- fread("../../Result/profile/final_species_trim.tsv")
```


### Function
```{r}
Maaslin2_fun <- function(metadata=phen,
                         profile=sp.prf,
                         outdir="Masslin2_species"){
  # metadata=phen
  # profile=sp.prf
  # outdir="Masslin2_species"
  
  sid <- intersect(metadata$SampleID, colnames(profile))

  phe <- metadata %>% filter(SampleID%in%sid) %>%
    droplevels()   
  
  prf <- profile %>% column_to_rownames("V1") %>%
    dplyr::select(as.character(phe$SampleID)) %>%
    rownames_to_column("Type") %>%
    filter(apply(select(., -one_of("Type")), 1, function(x){sum(x>0)/length(x)}) > 0.2) %>%
    column_to_rownames("Type")  %>% 
    t() %>% data.frame()
  
  # merge data by sampleID
  mdat <- left_join(phe, 
                   prf %>% rownames_to_column("SampleID"), 
                   by="SampleID") %>%
    column_to_rownames("SampleID")
  
  # choose mdat 
  input_data <- mdat[, c(ncol(phe):ncol(mdat))] 
  input_metadata <- mdat[, c(1:(ncol(phe)-1))]  
  
  fit_data <- Maaslin2(
    input_data, 
    input_metadata, 
    outdir,
    min_abundance = 1e-05,
    min_prevalence = 0.2,    
    transform = "AST",
    fixed_effects = c("Age"),
    random_effects = NULL,
    normalization = "TSS",
    analysis_method = "LM",
    max_significance = 0.25,
    correction = "BH",
    standardize = TRUE,
    cores = 1,
    plot_heatmap = TRUE,
    plot_scatter = TRUE,
    heatmap_first_n = 50)
}

Maaslin2_fun(metadata=phen,
             profile=sp.prf,
             outdir="Masslin2_species")
```


### Systemic information
```{r}
sessionInfo()
```


### Reference 

1. [MaAsLin2](https://huttenhower.sph.harvard.edu/maaslin)
