---
title: "Association between taxonomy and biocheimal: Spearman"
date: "Created: 2021-01-12 Modified: `r Sys.Date()`"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)

grp <- c("lupus", "Control")
grp.col <- c("#283891", "#C1272D")
```


### load data
```{r}
phen <- read.csv("../../Result/phenotype/phenotype_20200111.csv")
sp.prf <- fread("../../Result/profile/final_species_trim.tsv")
```


### Spearman correlation coefficient
```{r}
corFun <- function(tag, x, y){
  # tag <- "Age"
  # x <- phen
  # y <- sp.prf
  
  # choose data 
  colnames(x)[which(colnames(x)==tag)] <- "group" 
  id <- c("SampleID", "group")
  # get intersect by SampleID
  sid <- intersect(as.character(x$SampleID), colnames(y))

  phe <- x %>% filter(SampleID %in% sid) %>%
    dplyr::select(one_of(id)) %>% 
    filter(!is.na(group)) %>%
    droplevels()   
  
  prf <- y %>% dplyr::select(as.character(phe$SampleID)) %>%
    # resevred the rownames
    rownames_to_column("Type") %>%
    # occurence of rows more than 2 
    filter(apply(select(., -one_of("Type")), 1, function(x){sum(x>0)/length(x)}) > 0.2) %>%
    column_to_rownames("Type")  %>% 
    t() %>% data.frame()
  
  # merge data by sampleID
  dat <- left_join(phe, prf %>% rownames_to_column("SampleID"), by="SampleID") %>%
    dplyr::select(-one_of("SampleID"))
  
  # choose dat 
  datprf <- dat[, c(2:ncol(dat))] 
  datphe <- dat[, 1, F]  
  print(nrow(datphe))
  # cor calculate
  res <- apply(t(datprf), 1, function(x, phs){
    
    d <- cbind(phs, y = as.numeric(x))
    cor <- cor.test(as.numeric(d$y), 
                    as.numeric(d$group), 
                    method = "spearman")
    res <- c(as.numeric(cor$estimate), 
             as.numeric(cor$p.value))
    return(res)
  }, datphe) %>% t() %>% data.frame() %>%
    rownames_to_column("Type") %>% 
    mutate(Phenotype = tag)
    
  colnames(res)[2:3] <- c("Rho", "Pvalue")
  res$FDR <- p.adjust(res$Pvalue, method = "BH")
  
  res <- res %>% dplyr::select(Type, Phenotype, Rho, Pvalue, FDR)
  return(res)
}

# phenotype index to run spearman correlation coefficient
idx_names <- colnames(phen)[c(2, 5:30)]
sp.cor <- do.call(rbind, lapply(idx_names, corFun, phen, sp.prf %>% column_to_rownames("V1")))
DT::datatable(sp.cor)
```


### species
```{r}
dir <- "../../Result/permanova"
if(!dir.exists(dir)){
  dir.create(dir)
}

sp.per <- Permanova_fun(profile = sp.prf)
DT::datatable(sp.per)
sp.path <- paste(dir, "species_permanova.csv", sep = "/")
write.csv(sp.per, file = sp.path, row.names = T)
```




### version
```{r}
sessionInfo()
```

